### ISSUE TITLE
Question about this library - uses AppAuth-Android ? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [geniushkg/github-oauth#11]
Does it use this:
https://github.com/openid/AppAuth-Android
?

**Comment by geniushkg** [comment]
Nope, it doesn't use any library underneath.

**Comment by AndroidDeveloperLB** [comment]
Is it possible though? This library of Google seems to handle everything for you, including token refresh.
I didn't get how to use it though.

Aside from login, does the current library handle more things that are related to OAUTH ?
Also, seems that I need GITHUB_ID and GITHUB_SECRET. You wrote on the page of the repository that I need to register a new app on Github. Is it [here](https://github.com/settings/apps/new), using [this ](https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app/)tutorial?

Which settings are recommended to use there? Suppose I want to search a user by email, do I need to tick there something?

**Comment by geniushkg** [comment]
Sorry, some communication gaps maybe. 

A) [Current library](https://github.com/geniushkg/github-oauth)   -  I built is just a wrapper it only handles OAuth login with role/scope permission only for GitHub API. 

B) I don't know if the library you mentioned is able to do everything but it seems general purpose for multiple providers. maybe this video gives you some correct direction for what you intend to do : [youtube explaination](https://www.youtube.com/watch?v=996OiexHze0)

**Comment by AndroidDeveloperLB** [comment]
@geniushkg 
A) I see. Can you please update the main page to include the links I've mentioned? Also, can you please let me know what I should do on this website of creating an app? I want to try it out...

B) I see. Do you know perhaps of a sample that uses it for Github? Do you think it could be hard to implement it? The video isn't about Google's library solution. It seems general abut OAuth, and I think I already got the idea, just not the implementation itself .

Github sadly doesn't have a sample for Android, so I noticed both of these libraries and hoped to have a better way to try it out.

**Comment by geniushkg** [comment]
Updated Readme file 👍 

About sample, I am not sure

**Comment by AndroidDeveloperLB** [comment]
Google seems to have blocked WebView to use Oauth, but I think only for its own services:

https://auth0.com/blog/google-blocks-oauth-requests-from-embedded-browsers/

So I thought maybe it should be a good choice to use their library.
