### ISSUE TITLE
Disabled authorize button on Android.

### ISSUE THREAD

**Issue by darvid7** [geniushkg/github-oauth#2]
Hey,
I'm having an issue with authorization, I've checked my `client_id` and `client_secret` and am sure they are correct in my app.

In android (simulator and on my device) when I try to authenticate the authorize button is disabled.
<img width="200" alt="18765257_758923900934955_1860996768_o" src="https://cloud.githubusercontent.com/assets/11433468/26527053/f4309d56-43ce-11e7-856b-252ad1ce7028.png">

Works ok when I copy and paste the logged out link (below) into a web browser.
`https://github.com/login/oauth/authorize?client_id=MY_CLIENT_ID&scope=user%2Cpublic_repo`

<img width="200" alt="screen shot 2017-05-28 at 5 49 12 pm" src="https://cloud.githubusercontent.com/assets/11433468/26527049/e3947a62-43ce-11e7-9c28-e490560e99f0.png">

Im getting this as my response: `{"error":"bad_verification_code","error_description":"The code passed is incorrect or expired.","error_uri":"https://developer.github.com/v3/oauth/#bad-verification-code"}`.

Any ideas would be great,
Thanks!

**Comment by darvid7** [comment]
#3 prevents crashes if users click on links in the webview, however this also disabled the authorise button. I believe the authorise button was disabled because js was not enabled on the webview, but it wasn't enabled before either so not too sure. Either way, enabling js fixes this.

**Comment by geniushkg** [comment]
Thanks for update, will mention on Readme
